// Bundle local CommonJS modules; Obsidian resolves its own external editor modules.
const fs = require('fs');
const path = require('path');
const modules = ['annotations', 'core', 'bridge', 'follow-up', 'stable-view', 'main-source'];
const factories = modules.map(name => `${JSON.stringify('./' + name)}: function(module, exports, require) {\n${fs.readFileSync(path.join(__dirname, name + '.js'), 'utf8')}\n}`).join(',\n');
const output = `// Generated by node build.js. Edit main-source.js, core.js or bridge.js.\n'use strict';\nconst externalRequire = require;\nconst factories = {${factories}};\nconst cache = {};\nfunction localRequire(id) {\n if (!factories[id]) return externalRequire(id);\n if (!cache[id]) { cache[id] = { exports: {} }; factories[id](cache[id], cache[id].exports, localRequire); }\n return cache[id].exports;\n}\nmodule.exports = localRequire('./main-source');\n`;
fs.writeFileSync(path.join(__dirname, 'main.js'), output);
console.log('Built main.js');
